# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  push:
  # Triggers the workflow on push or pull request events but only for the main branch
    branches:
      - main
    paths:
      - 'projects/ngx-rating/**'
      - '.github/workflows/publish.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run ng build with npx
        run: npx ng build ngx-rating

      - name: Generate registry access file
        run: printf '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ./.npmrc

      - name: Generate tarball
        run: npm pack
        working-directory: ./dist/ngx-rating
        env:
          NPM_TOKEN: ${{ secrets.NPM_DAVIDE_ROSSI_AUTOMATION_TOKEN }}
        
      - name: Publish on npm
        run: npm publish --access public --tarball ./dist/ngx-rating/$(ls ./dist/ngx-rating | grep -E aesys.*\.tgz)
        env:
          NPM_TOKEN: ${{ secrets.NPM_DAVIDE_ROSSI_AUTOMATION_TOKEN }}
          
        
